spring.application.name=ClinicCare

# Supabase Connection
# TODO: Replace [PROJECT_ID] and [YOUR_PASSWORD] with your actual Supabase credentials
# Supabase (PostgreSQL) Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.upknlccealpiaxjnbrga
spring.datasource.password=@BajariasWayne2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
